version: '3'
services:

  #PHP Service
  covid19-dsp-app:
    build:
      context: ./../docker/
      dockerfile: ./../docker/Dockerfile
    image: covid19_dsp/php
    container_name: covid19-dsp-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - ./../docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  covid19-dsp-webserver:
    image: nginx:alpine
    container_name: covid19-dsp-webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../:/var/www
      - ./../docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
